"""Workspace scaffolding tool.

Creates a minimal starter project (python or node) inside the workspace so the
CODE engine has somewhere to generate into.
"""

from __future__ import annotations

from .base import Tool, ToolResult

_PY_FILES = {
    "main.py": '"""Entry point."""\n\n\ndef main() -> None:\n    print("Hello from {name}")\n\n\nif __name__ == "__main__":\n    main()\n',
    "requirements.txt": "",
    "README.md": "# {name}\n\nGenerated by SABI.\n",
}

_NODE_FILES = {
    "index.js": 'console.log("Hello from {name}");\n',
    "package.json": '{\n  "name": "{name}",\n  "version": "0.1.0",\n  "main": "index.js"\n}\n',
    "README.md": "# {name}\n\nGenerated by SABI.\n",
}


class ScaffoldTool(Tool):
    name = "scaffold"
    description = "Scaffold a minimal starter project (kind=python|node) in the workspace."

    def run(self, name: str, kind: str = "python", **_) -> ToolResult:
        try:
            root = self._safe_path(name)
            root.mkdir(parents=True, exist_ok=True)
            files = _PY_FILES if kind == "python" else _NODE_FILES
            created = []
            for rel, template in files.items():
                (root / rel).write_text(template.replace("{name}", name), encoding="utf-8")
                created.append(rel)
            return ToolResult(
                True,
                output=f"scaffolded {kind} project '{name}': " + ", ".join(created),
                data={"path": str(root), "files": created},
            )
        except Exception as exc:  # noqa: BLE001
            return ToolResult(False, error=str(exc))
